- name: install and configure kibana
  hosts: kibana
  become: true
  tasks:
    - name: download kibana
      shell: "ls | grep -q '^kibana-{{ elk_version }}-x86_64.rpm$' || \
              wget https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_version }}-x86_64.rpm"
    - name: install kibana
      shell: "rpm -i kibana-{{ elk_version }}-x86_64.rpm"
      # ignore error if the package is already installed
      ignore_errors: true
    - name: copy kibana config
      copy:
        src: "{{ kibana_config }}"
        dest: /etc/kibana/kibana.yml
    - name: start kibana via systemctl
      shell: "sudo /bin/systemctl daemon-reload && \
              sudo systemctl start kibana.service"
