- name: setup nginx and copy a webpage
  hosts: services
  become: true
  tasks:
    - name: install nginx
      shell: amazon-linux-extras install nginx1 -y
      ignore_errors: true
    - name: copy website
      copy: 
        src: index.html
        dest: /usr/share/nginx/html/
    - name: start nginx
      service:
        name: nginx
        state: started
