- name: setup a python web scraper
  hosts: services
  become: true

  tasks:
    - name: install git
      shell: yum install git -y
    
    - name: clone the scraper's repository and cd into it
      shell: ls | grep -q scraper-demo || git clone https://github.com/adams1mon/scraper-demo.git
    
    - name: install dependencies
      shell: pip3 install -r scraper-demo/requirements.txt

    - name: change /var/log directory permissions (so logs can be written)
      shell: chmod a+w /var/log     

    - name: start crawler with 'nohup', so it runs after logging out
      shell: cd scraper-demo && nohup ./run_crawler.sh >/dev/null & 
    
    - name: install and start filebeat
      include_role:
        name: filebeat
      vars:
        log_path: /var/log/scraper/*.log
          
