- name: download and setup metricbeat
  hosts: services
  become: true
  tasks:
    - name: download metricbeat
      shell: "ls | grep -q '^metricbeat-{{ elk_version }}-x86_64.rpm$' || \
              wget https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-{{ elk_version }}-x86_64.rpm"
    - name: install metricbeat
      shell: "rpm -i metricbeat-{{ elk_version }}-x86_64.rpm"
      ignore_errors: true
    - name: copy metricbeat config file
      copy:
        src: "{{ metricbeat_config }}"
        dest: /etc/metricbeat/metricbeat.yml
    - name: enable metricbeat "system" module
      shell: metricbeat modules enable system
    - name: start metricbeat
      service:
        name: metricbeat
        state: started
      
