- name: ansible play to install and configure elasticsearch
  hosts: elasticsearch
  become: true
  vars: 
    elk_version: 7.10.1
  tasks:
    - name: download elasticsearch
      shell: "wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{elk_version}}-x86_64.rpm"
    - name: install elasticsearch
      shell: "rpm -i elasticsearch-{{elk_version}}-x86_64.rpm"
    - name: copy jvm options
      copy: 
        src: jvm.options
        dest: /etc/elasticsearch/jvm.options.d/
    - name: start elasticsearch via systemctl
      shell: "sudo /bin/systemctl daemon-reload && \
              sudo systemctl start elasticsearch.service"
