- name: ansible play to install and configure elasticsearch
  hosts: elasticsearch
  become: true
  tasks:
    - name: download kibana
      shell: "wget https://artifacts.elastic.co/downloads/kibana/kibana-{{elk_version}}-x86_64.rpm"
    - name: install kibana
      shell: "rpm -i kibana-{{elk_version}}-x86_64.rpm"
    - name: copy jvm options
      copy: 
        src: jvm.options
        dest: /etc/kibana/jvm.options.d/
    - name: start kibana via systemctl
      shell: "sudo /bin/systemctl daemon-reload && \
              sudo systemctl start kibana.service"
